version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: