version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: nginx_container
    networks:
      - my_bridge_network
    ports:
      - "8080:80"

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge