global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']    # Адрес, где работает Prometheus

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']    # Адрес, где работает cAdvisor